require('dotenv').config();
const mongoose = require('mongoose');
const bcrypt = require('bcryptjs');
const Employee = require('./models/Employee');
const Division = require('./models/Division');
const User = require('./models/User');
const Grade = require('./models/Grade');

const seedData = async () => {
  try {
    await mongoose.connect(process.env.MONGO_URI || 'mongodb://localhost:27017/employee_management');

    // Clear non-admin data
    await Employee.deleteMany({});
    await Division.deleteMany({});
    await User.deleteMany({ role: { $ne: 'admin' } });
    await Grade.deleteMany({});

    // Seed grades
    const grades = [
      { name: 'Manager', description: 'Directeur de division' },
      { name: 'Manager RH', description: 'Directeur des ressources humaines' },
      { name: 'Analyste', description: 'Analyste de données' },
      { name: 'Technicienne', description: 'Spécialiste technique' },
      { name: 'Consultant', description: 'Consultant externe' },
      { name: 'Analyste Financier', description: 'Analyste financier' },
      { name: 'Coordinatrice', description: 'Coordinatrice de projets' },
      { name: 'Assistante RH', description: 'Assistante des ressources humaines' },
      { name: 'Architecte', description: 'Architecte urbain' },
      { name: 'Assistante', description: 'Assistante générale' },
    ];
    const insertedGrades = await Grade.insertMany(grades);
    console.log('Grades inserted:', insertedGrades.length);

    // Check or update admin user
    let admin = await User.findOne({ email: 'admin@example.com' });
    const newPassword = 'admin123'; // Plain text password
    const newPasswordHash = await bcrypt.hash(newPassword, 10);
    console.log('Hash generated for admin123:', newPasswordHash);

    if (!admin) {
      admin = new User({
        name: 'Utilisateur Admin',
        email: 'admin@example.com',
        password: newPassword, // Set plain text to trigger hash in pre-save
        role: 'admin',
      });
      await admin.save();
      console.log('Admin user created: email=admin@example.com');
    } else {
      admin.password = newPassword; // Set plain text to trigger re-hash
      admin.markModified('password'); // Explicitly mark as modified
      await admin.save();
      console.log('Admin password updated to match admin123');
    }

    // Seed all 10 divisions with French descriptions (original 8 + new Cabinet and SG)
    const divisions = [
      { name: 'DAEC', currentProject: 'Coordination Administrative', managerId: null, employeeIds: [], isSeeded: true },
      { name: 'DAI', currentProject: 'Analyse d’Infrastructure', managerId: null, employeeIds: [], isSeeded: true },
      { name: 'DAS', currentProject: 'Systèmes de Sécurité', managerId: null, employeeIds: [], isSeeded: true },
      { name: 'DCT', currentProject: 'Contrôle Technique', managerId: null, employeeIds: [], isSeeded: true },
      { name: 'DFL', currentProject: 'Logistique Financière', managerId: null, employeeIds: [], isSeeded: true },
      { name: 'DPE', currentProject: 'Évaluation des Performances', managerId: null, employeeIds: [], isSeeded: true },
      { name: 'DRHF', currentProject: 'Cadre des Ressources Humaines', managerId: null, employeeIds: [], isSeeded: true },
      { name: 'DUE', currentProject: 'Développement Urbain', managerId: null, employeeIds: [], isSeeded: true },
      { name: 'Cabinet', currentProject: 'Gestion Stratégique', managerId: null, employeeIds: [], isSeeded: true },
      { name: 'SG', currentProject: 'Coordination Générale', managerId: null, employeeIds: [], isSeeded: true },
    ];

    const insertedDivisions = await Division.insertMany(divisions);
    console.log('Divisions inserted:', insertedDivisions.length);

    // Map division names to their IDs for employee assignment
    const divisionMap = insertedDivisions.reduce((map, div) => {
      map[div.name] = div._id;
      return map;
    }, {});

    // Seed all 39 employees with French data, image, and anciennete (35 original + 4 new for Cabinet and SG)
    const employees = [
      {
        nomComplet: 'Ahmed Benali',
        dateNaissance: new Date('1975-03-15'),
        sexe: 'Homme',
        grade: 'Manager',
        dateRecrutement: new Date('2010-06-01'),
        diplome: 'Master en Informatique',
        affectation: 'Gestion Administrative',
        situationFamiliale: 'Marié',
        missionPoste: 'Superviser la coordination administrative',
        formationInitiale: 'École Nationale d’Ingénieurs',
        activitePrincipale: 'Gestion des équipes administratives',
        cin: 'AB123456',
        ppr: 'PPR001',
        adresse: 'Rue Hassan II, Casablanca',
        email: 'ahmed.benali@example.com',
        numeroTelephone: '+212600123456',
        experienceExterne: '5 années chez TechCorp',
        experienceInterne: '10 années',
        divisionId: divisionMap['DAEC'],
        informationsSupplementaires: ['Certificat en gestion de projet'],
        image: 'https://via.placeholder.com/150?text=Ahmed+Benali',
        anciennete: Math.floor((new Date('2025-06-02') - new Date('2010-06-01')) / (1000 * 60 * 60 * 24 * 365)),
      },
      {
        nomComplet: 'Fatima Zahra',
        dateNaissance: new Date('1985-07-22'),
        sexe: 'Femme',
        grade: 'Analyste',
        dateRecrutement: new Date('2015-09-10'),
        diplome: 'Licence en Gestion',
        affectation: 'Analyse de données',
        situationFamiliale: 'Célibataire',
        missionPoste: 'Analyser les performances',
        formationInitiale: 'Université Mohammed V',
        activitePrincipale: 'Rapports et statistiques',
        cin: 'FZ789012',
        ppr: 'PPR002',
        adresse: 'Avenue Mohammed VI, Rabat',
        email: 'fatima.zahra@example.com',
        numeroTelephone: '+212600789012',
        experienceExterne: '2 années chez DataCorp',
        experienceInterne: '5 années',
        divisionId: divisionMap['DAEC'],
        informationsSupplementaires: ['Formation en analyse de données'],
        image: 'https://via.placeholder.com/150?text=Fatima+Zahra',
        anciennete: Math.floor((new Date('2025-06-02') - new Date('2015-09-10')) / (1000 * 60 * 60 * 24 * 365)),
      },
      {
        nomComplet: 'Mohammed El Idrissi',
        dateNaissance: new Date('1972-11-05'),
        sexe: 'Homme',
        grade: 'Manager',
        dateRecrutement: new Date('2008-03-15'),
        diplome: 'Master en Gestion',
        affectation: 'Gestion de projet',
        situationFamiliale: 'Marié',
        missionPoste: 'Superviser les projets d’infrastructure',
        formationInitiale: 'École Hassania des Travaux Publics',
        activitePrincipale: 'Coordination des équipes',
        cin: 'ME345678',
        ppr: 'PPR003',
        adresse: 'Rue Al Massira, Marrakech',
        email: 'mohammed.elidrissi@example.com',
        numeroTelephone: '+212600345678',
        experienceExterne: '7 années chez InfraCorp',
        experienceInterne: '12 années',
        divisionId: divisionMap['DAI'],
        informationsSupplementaires: ['Certificat en gestion de projet'],
        image: 'https://via.placeholder.com/150?text=Mohammed+El+Idrissi',
        anciennete: Math.floor((new Date('2025-06-02') - new Date('2008-03-15')) / (1000 * 60 * 60 * 24 * 365)),
      },
      {
        nomComplet: 'Aicha Bennani',
        dateNaissance: new Date('1978-04-18'),
        sexe: 'Femme',
        grade: 'Technicienne',
        dateRecrutement: new Date('2013-12-01'),
        diplome: 'BTS en Sécurité',
        affectation: 'Sécurité des systèmes',
        situationFamiliale: 'Divorcé',
        missionPoste: 'Maintenir les équipements de sécurité',
        formationInitiale: 'Institut Technique de Rabat',
        activitePrincipale: 'Contrôle des installations',
        cin: 'AB901234',
        ppr: 'PPR004',
        adresse: 'Rue Ibn Sina, Fès',
        email: 'aicha.bennani@example.com',
        numeroTelephone: '+212600901234',
        experienceExterne: '3 années chez SecurCorp',
        experienceInterne: '7 années',
        divisionId: divisionMap['DAI'],
        informationsSupplementaires: ['Formation en maintenance'],
        image: 'https://via.placeholder.com/150?text=Aicha+Bennani',
        anciennete: Math.floor((new Date('2025-06-02') - new Date('2013-12-01')) / (1000 * 60 * 60 * 24 * 365)),
      },
      {
        nomComplet: 'Youssef Amrani',
        dateNaissance: new Date('1987-09-30'),
        sexe: 'Homme',
        grade: 'Consultant',
        dateRecrutement: new Date('2017-05-20'),
        diplome: 'Master en Sécurité',
        affectation: 'Audit de sécurité',
        situationFamiliale: 'Célibataire',
        missionPoste: 'Évaluer les risques de sécurité',
        formationInitiale: 'Université Al Akhawayn',
        activitePrincipale: 'Audit et conformité',
        cin: 'YA567890',
        ppr: 'PPR005',
        adresse: 'Avenue Allal Ben Abdellah, Tanger',
        email: 'youssef.amrani@example.com',
        numeroTelephone: '+212600567890',
        experienceExterne: '1 année chez SafeCorp',
        experienceInterne: '3 années',
        divisionId: divisionMap['DAS'],
        informationsSupplementaires: ['Certificat en audit de sécurité'],
        image: 'https://via.placeholder.com/150?text=Youssef+Amrani',
        anciennete: Math.floor((new Date('2025-06-02') - new Date('2017-05-20')) / (1000 * 60 * 60 * 24 * 365)),
      },
      {
        nomComplet: 'Laila Chraibi',
        dateNaissance: new Date('1977-02-12'),
        sexe: 'Femme',
        grade: 'Manager',
        dateRecrutement: new Date('2012-08-15'),
        diplome: 'Master en Génie Civil',
        affectation: 'Gestion de sécurité',
        situationFamiliale: 'Marié',
        missionPoste: 'Superviser les systèmes de sécurité',
        formationInitiale: 'École Mohammedia d’Ingénieurs',
        activitePrincipale: 'Gestion des équipes de sécurité',
        cin: 'LC123456',
        ppr: 'PPR006',
        adresse: 'Rue Abdelmoumen, Casablanca',
        email: 'laila.chraibi@example.com',
        numeroTelephone: '+212600123456',
        experienceExterne: '4 années chez BuildCorp',
        experienceInterne: '8 années',
        divisionId: divisionMap['DAS'],
        informationsSupplementaires: ['Certificat en gestion de sécurité'],
        image: 'https://via.placeholder.com/150?text=Laila+Chraibi',
        anciennete: Math.floor((new Date('2025-06-02') - new Date('2012-08-15')) / (1000 * 60 * 60 * 24 * 365)),
      },
      {
        nomComplet: 'Khalid Saidi',
        dateNaissance: new Date('1974-06-25'),
        sexe: 'Homme',
        grade: 'Manager',
        dateRecrutement: new Date('2011-10-01'),
        diplome: 'BTS en Mécanique',
        affectation: 'Gestion technique',
        situationFamiliale: 'Marié',
        missionPoste: 'Superviser le contrôle technique',
        formationInitiale: 'Institut de Technologie Appliquée',
        activitePrincipale: 'Gestion des équipes techniques',
        cin: 'KS789012',
        ppr: 'PPR007',
        adresse: 'Rue Mohammed V, Agadir',
        email: 'khalid.saidi@example.com',
        numeroTelephone: '+212600789012',
        experienceExterne: '6 années chez MechCorp',
        experienceInterne: '9 années',
        divisionId: divisionMap['DCT'],
        informationsSupplementaires: ['Formation en mécanique avancée'],
        image: 'https://via.placeholder.com/150?text=Khalid+Saidi',
        anciennete: Math.floor((new Date('2025-06-02') - new Date('2011-10-01')) / (1000 * 60 * 60 * 24 * 365)),
      },
      {
        nomComplet: 'Nadia El Fassi',
        dateNaissance: new Date('1986-12-03'),
        sexe: 'Femme',
        grade: 'Analyste Financier',
        dateRecrutement: new Date('2016-04-10'),
        diplome: 'Master en Finance',
        affectation: 'Gestion financière',
        situationFamiliale: 'Célibataire',
        missionPoste: 'Analyser les flux financiers',
        formationInitiale: 'École Nationale de Commerce et de Gestion',
        activitePrincipale: 'Budgétisation et rapports',
        cin: 'NE345678',
        ppr: 'PPR008',
        adresse: 'Avenue des FAR, Rabat',
        email: 'nadia.elfassi@example.com',
        numeroTelephone: '+212600345678',
        experienceExterne: '2 années chez FinCorp',
        experienceInterne: '4 années',
        divisionId: divisionMap['DCT'],
        informationsSupplementaires: ['Certificat en finance'],
        image: 'https://via.placeholder.com/150?text=Nadia+El+Fassi',
        anciennete: Math.floor((new Date('2025-06-02') - new Date('2016-04-10')) / (1000 * 60 * 60 * 24 * 365)),
      },
      {
        nomComplet: 'Omar Tazi',
        dateNaissance: new Date('1976-08-08'),
        sexe: 'Homme',
        grade: 'Manager',
        dateRecrutement: new Date('2014-02-20'),
        diplome: 'Licence en Logistique',
        affectation: 'Gestion logistique',
        situationFamiliale: 'Marié',
        missionPoste: 'Superviser la logistique financière',
        formationInitiale: 'Université Ibn Zohr',
        activitePrincipale: 'Gestion des équipes logistiques',
        cin: 'OT901234',
        ppr: 'PPR009',
        adresse: 'Rue Ibn Battuta, Marrakech',
        email: 'omar.tazi@example.com',
        numeroTelephone: '+212600901234',
        experienceExterne: '5 années chez LogiCorp',
        experienceInterne: '6 années',
        divisionId: divisionMap['DFL'],
        informationsSupplementaires: ['Certificat en logistique'],
        image: 'https://via.placeholder.com/150?text=Omar+Tazi',
        anciennete: Math.floor((new Date('2025-06-02') - new Date('2014-02-20')) / (1000 * 60 * 60 * 24 * 365)),
      },
      {
        nomComplet: 'Sara Lahlou',
        dateNaissance: new Date('1987-05-17'),
        sexe: 'Femme',
        grade: 'Coordinatrice',
        dateRecrutement: new Date('2018-07-01'),
        diplome: 'Licence en Management',
        affectation: 'Coordination de projets',
        situationFamiliale: 'Célibataire',
        missionPoste: 'Coordonner les équipes financières',
        formationInitiale: 'Université Cadi Ayyad',
        activitePrincipale: 'Planification et suivi',
        cin: 'SL567890',
        ppr: 'PPR010',
        adresse: 'Avenue Al Qods, Fès',
        email: 'sara.lahlou@example.com',
        numeroTelephone: '+212600567890',
        experienceExterne: '1 année chez CoordCorp',
        experienceInterne: '2 années',
        divisionId: divisionMap['DFL'],
        informationsSupplementaires: ['Formation en gestion de projets'],
        image: 'https://via.placeholder.com/150?text=Sara+Lahlou',
        anciennete: Math.floor((new Date('2025-06-02') - new Date('2018-07-01')) / (1000 * 60 * 60 * 24 * 365)),
      },
      {
        nomComplet: 'Hassan Bouzidi',
        dateNaissance: new Date('1971-10-14'),
        sexe: 'Homme',
        grade: 'Manager',
        dateRecrutement: new Date('2009-11-05'),
        diplome: 'Master en Évaluation',
        affectation: 'Gestion d’évaluation',
        situationFamiliale: 'Marié',
        missionPoste: 'Superviser l’évaluation des performances',
        formationInitiale: 'École Nationale de Gestion',
        activitePrincipale: 'Gestion des équipes d’évaluation',
        cin: 'HB123456',
        ppr: 'PPR011',
        adresse: 'Rue Al Irfane, Tanger',
        email: 'hassan.bouzidi@example.com',
        numeroTelephone: '+212600123456',
        experienceExterne: '8 années chez EvalCorp',
        experienceInterne: '11 années',
        divisionId: divisionMap['DPE'],
        informationsSupplementaires: ['Certificat en évaluation'],
        image: 'https://via.placeholder.com/150?text=Hassan+Bouzidi',
        anciennete: Math.floor((new Date('2025-06-02') - new Date('2009-11-05')) / (1000 * 60 * 60 * 24 * 365)),
      },
      {
        nomComplet: 'Zineb Alaoui',
        dateNaissance: new Date('1981-03-29'),
        sexe: 'Femme',
        grade: 'Consultant',
        dateRecrutement: new Date('2015-01-15'),
        diplome: 'Master en Ressources Humaines',
        affectation: 'Gestion du personnel',
        situationFamiliale: 'Marié',
        missionPoste: 'Gérer les processus RH',
        formationInitiale: 'Université Hassan II',
        activitePrincipale: 'Recrutement et formation',
        cin: 'ZA789012',
        ppr: 'PPR012',
        adresse: 'Avenue Mohammed V, Casablanca',
        email: 'zineb.alaoui@example.com',
        numeroTelephone: '+212600789012',
        experienceExterne: '3 années chez HRCorp',
        experienceInterne: '5 années',
        divisionId: divisionMap['DPE'],
        informationsSupplementaires: ['Formation en gestion RH'],
        image: 'https://via.placeholder.com/150?text=Zineb+Alaoui',
        anciennete: Math.floor((new Date('2025-06-02') - new Date('2015-01-15')) / (1000 * 60 * 60 * 24 * 365)),
      },
      {
        nomComplet: 'Rachid Mernissi',
        dateNaissance: new Date('1969-07-07'),
        sexe: 'Homme',
        grade: 'Manager RH',
        dateRecrutement: new Date('2007-04-10'),
        diplome: 'Master en Gestion RH',
        affectation: 'Stratégie RH',
        situationFamiliale: 'Marié',
        missionPoste: 'Développer les politiques RH',
        formationInitiale: 'École Nationale de Commerce',
        activitePrincipale: 'Planification stratégique',
        cin: 'RM345678',
        ppr: 'PPR013',
        adresse: 'Rue Al Wahda, Rabat',
        email: 'rachid.mernissi@example.com',
        numeroTelephone: '+212600345678',
        experienceExterne: '10 années chez StratCorp',
        experienceInterne: '13 années',
        divisionId: divisionMap['DRHF'],
        informationsSupplementaires: ['Certificat en stratégie RH'],
        image: 'https://via.placeholder.com/150?text=Rachid+Mernissi',
        anciennete: Math.floor((new Date('2025-06-02') - new Date('2007-04-10')) / (1000 * 60 * 60 * 24 * 365)),
      },
      {
        nomComplet: 'Meryem Kabbaj',
        dateNaissance: new Date('1991-11-20'),
        sexe: 'Femme',
        grade: 'Assistante RH',
        dateRecrutement: new Date('2019-03-01'),
        diplome: 'Licence en Gestion',
        affectation: 'Administration RH',
        situationFamiliale: 'Célibataire',
        missionPoste: 'Gérer les dossiers du personnel',
        formationInitiale: 'Université Abdelmalek Essaadi',
        activitePrincipale: 'Gestion administrative',
        cin: 'MK901234',
        ppr: 'PPR014',
        adresse: 'Avenue Hassan I, Tétouan',
        email: 'meryem.kabbaj@example.com',
        numeroTelephone: '+212600901234',
        experienceExterne: '1 année chez AdminCorp',
        experienceInterne: '1 année',
        divisionId: divisionMap['DRHF'],
        informationsSupplementaires: ['Formation en gestion administrative'],
        image: 'https://via.placeholder.com/150?text=Meryem+Kabbaj',
        anciennete: Math.floor((new Date('2025-06-02') - new Date('2019-03-01')) / (1000 * 60 * 60 * 24 * 365)),
      },
      {
        nomComplet: 'Said Cherkaoui',
        dateNaissance: new Date('1975-01-09'),
        sexe: 'Homme',
        grade: 'Manager',
        dateRecrutement: new Date('2010-09-15'),
        diplome: 'Master en Urbanisme',
        affectation: 'Gestion urbaine',
        situationFamiliale: 'Marié',
        missionPoste: 'Superviser le développement urbain',
        formationInitiale: 'École d’Architecture de Rabat',
        activitePrincipale: 'Gestion des équipes d’urbanisme',
        cin: 'SC567890',
        ppr: 'PPR015',
        adresse: 'Rue Al Amal, Marrakech',
        email: 'said.cherkaoui@example.com',
        numeroTelephone: '+212600567890',
        experienceExterne: '5 années chez UrbanCorp',
        experienceInterne: '10 années',
        divisionId: divisionMap['DUE'],
        informationsSupplementaires: ['Certificat en urbanisme'],
        image: 'https://via.placeholder.com/150?text=Said+Cherkaoui',
        anciennete: Math.floor((new Date('2025-06-02') - new Date('2010-09-15')) / (1000 * 60 * 60 * 24 * 365)),
      },
      {
        nomComplet: 'Asma Bennacer',
        dateNaissance: new Date('1986-06-13'),
        sexe: 'Femme',
        grade: 'Architecte',
        dateRecrutement: new Date('2016-11-01'),
        diplome: 'Master en Architecture',
        affectation: 'Conception urbaine',
        situationFamiliale: 'Célibataire',
        missionPoste: 'Développer des projets architecturaux',
        formationInitiale: 'École Nationale d’Architecture',
        activitePrincipale: 'Conception et planification',
        cin: 'AB123457',
        ppr: 'PPR016',
        adresse: 'Avenue Al Moustakbal, Casablanca',
        email: 'asma.bennacer@example.com',
        numeroTelephone: '+212600123456',
        experienceExterne: '2 années chez ArchiCorp',
        experienceInterne: '4 années',
        divisionId: divisionMap['DUE'],
        informationsSupplementaires: ['Formation en architecture'],
        image: 'https://via.placeholder.com/150?text=Asma+Bennacer',
        anciennete: Math.floor((new Date('2025-06-02') - new Date('2016-11-01')) / (1000 * 60 * 60 * 24 * 365)),
      },
      {
        nomComplet: 'Karim Essaghir',
        dateNaissance: new Date('1983-09-10'),
        sexe: 'Homme',
        grade: 'Analyste',
        dateRecrutement: new Date('2016-03-01'),
        diplome: 'Licence en Informatique',
        affectation: 'Analyse de données',
        situationFamiliale: 'Marié',
        missionPoste: 'Analyser les données administratives',
        formationInitiale: 'Université Ibn Tofail',
        activitePrincipale: 'Rapports et analyses',
        cin: 'KE901235',
        ppr: 'PPR017',
        adresse: 'Rue Al Khawarizmi, Kenitra',
        email: 'karim.essaghir@example.com',
        numeroTelephone: '+212600901235',
        experienceExterne: '3 années chez InfoCorp',
        experienceInterne: '6 années',
        divisionId: divisionMap['DAEC'],
        informationsSupplementaires: ['Certificat en informatique'],
        image: 'https://via.placeholder.com/150?text=Karim+Essaghir',
        anciennete: Math.floor((new Date('2025-06-02') - new Date('2016-03-01')) / (1000 * 60 * 60 * 24 * 365)),
      },
      {
        nomComplet: 'Hanan Riad',
        dateNaissance: new Date('1990-02-25'),
        sexe: 'Femme',
        grade: 'Coordinatrice',
        dateRecrutement: new Date('2020-01-15'),
        diplome: 'Licence en Gestion de Projets',
        affectation: 'Coordination administrative',
        situationFamiliale: 'Célibataire',
        missionPoste: 'Coordonner les tâches administratives',
        formationInitiale: 'Université Al Quaraouiyine',
        activitePrincipale: 'Planification et suivi',
        cin: 'HR567891',
        ppr: 'PPR018',
        adresse: 'Avenue Al Massira, Fès',
        email: 'hanan.riad@example.com',
        numeroTelephone: '+212600567891',
        experienceExterne: '1 année chez PlanCorp',
        experienceInterne: '2 années',
        divisionId: divisionMap['DAEC'],
        informationsSupplementaires: ['Formation en gestion de projets'],
        image: 'https://via.placeholder.com/150?text=Hanan+Riad',
        anciennete: Math.floor((new Date('2025-06-02') - new Date('2020-01-15')) / (1000 * 60 * 60 * 24 * 365)),
      },
      {
        nomComplet: 'Ilyas Mansour',
        dateNaissance: new Date('1980-05-18'),
        sexe: 'Homme',
        grade: 'Technicienne',
        dateRecrutement: new Date('2013-07-01'),
        diplome: 'BTS en Génie Civil',
        affectation: 'Infrastructure technique',
        situationFamiliale: 'Marié',
        missionPoste: 'Maintenir les infrastructures',
        formationInitiale: 'Institut Technique de Casablanca',
        activitePrincipale: 'Maintenance technique',
        cin: 'IM123458',
        ppr: 'PPR019',
        adresse: 'Rue Al Amane, Rabat',
        email: 'ilyas.mansour@example.com',
        numeroTelephone: '+212600123458',
        experienceExterne: '4 années chez BuildTech',
        experienceInterne: '8 années',
        divisionId: divisionMap['DAI'],
        informationsSupplementaires: ['Formation en génie civil'],
        image: 'https://via.placeholder.com/150?text=Ilyas+Mansour',
        anciennete: Math.floor((new Date('2025-06-02') - new Date('2013-07-01')) / (1000 * 60 * 60 * 24 * 365)),
      },
      {
        nomComplet: 'Sanae Idrissi',
        dateNaissance: new Date('1988-11-30'),
        sexe: 'Femme',
        grade: 'Analyste',
        dateRecrutement: new Date('2018-02-10'),
        diplome: 'Master en Statistiques',
        affectation: 'Analyse de données',
        situationFamiliale: 'Marié',
        missionPoste: 'Analyser les données d’infrastructure',
        formationInitiale: 'Université Mohammed VI',
        activitePrincipale: 'Rapports statistiques',
        cin: 'SI789013',
        ppr: 'PPR020',
        adresse: 'Avenue Al Haouz, Marrakech',
        email: 'sanae.idrissi@example.com',
        numeroTelephone: '+212600789013',
        experienceExterne: '2 années chez StatCorp',
        experienceInterne: '3 années',
        divisionId: divisionMap['DAI'],
        informationsSupplementaires: ['Certificat en statistiques'],
        image: 'https://via.placeholder.com/150?text=Sanae+Idrissi',
        anciennete: Math.floor((new Date('2025-06-02') - new Date('2018-02-10')) / (1000 * 60 * 60 * 24 * 365)),
      },
      {
        nomComplet: 'Adil Zaki',
        dateNaissance: new Date('1982-04-22'),
        sexe: 'Homme',
        grade: 'Technicienne',
        dateRecrutement: new Date('2015-06-01'),
        diplome: 'BTS en Sécurité',
        affectation: 'Sécurité des systèmes',
        situationFamiliale: 'Marié',
        missionPoste: 'Maintenir les systèmes de sécurité',
        formationInitiale: 'Institut Technique de Tanger',
        activitePrincipale: 'Maintenance et contrôle',
        cin: 'AZ345679',
        ppr: 'PPR021',
        adresse: 'Rue Al Fath, Tanger',
        email: 'adil.zaki@example.com',
        numeroTelephone: '+212600345679',
        experienceExterne: '3 années chez SecureTech',
        experienceInterne: '7 années',
        divisionId: divisionMap['DAS'],
        informationsSupplementaires: ['Formation en sécurité'],
        image: 'https://via.placeholder.com/150?text=Adil+Zaki',
        anciennete: Math.floor((new Date('2025-06-02') - new Date('2015-06-01')) / (1000 * 60 * 60 * 24 * 365)),
      },
      {
        nomComplet: 'Noura Benjelloun',
        dateNaissance: new Date('1990-08-15'),
        sexe: 'Femme',
        grade: 'Consultant',
        dateRecrutement: new Date('2019-05-01'),
        diplome: 'Master en Sécurité',
        affectation: 'Audit de sécurité',
        situationFamiliale: 'Célibataire',
        missionPoste: 'Évaluer les risques de sécurité',
        formationInitiale: 'Université Internationale de Rabat',
        activitePrincipale: 'Audit et recommandations',
        cin: 'NB901236',
        ppr: 'PPR022',
        adresse: 'Avenue Al Qods, Casablanca',
        email: 'noura.benjelloun@example.com',
        numeroTelephone: '+212600901236',
        experienceExterne: '1 année chez SafeTech',
        experienceInterne: '3 années',
        divisionId: divisionMap['DAS'],
        informationsSupplementaires: ['Certificat en audit'],
        image: 'https://via.placeholder.com/150?text=Noura+Benjelloun',
        anciennete: Math.floor((new Date('2025-06-02') - new Date('2019-05-01')) / (1000 * 60 * 60 * 24 * 365)),
      },
      {
        nomComplet: 'Badr Eddine',
        dateNaissance: new Date('1979-03-05'),
        sexe: 'Homme',
        grade: 'Technicienne',
        dateRecrutement: new Date('2012-09-01'),
        diplome: 'BTS en Mécanique',
        affectation: 'Contrôle technique',
        situationFamiliale: 'Marié',
        missionPoste: 'Contrôler les équipements techniques',
        formationInitiale: 'Institut Technique de Marrakech',
        activitePrincipale: 'Contrôle et maintenance',
        cin: 'BE567892',
        ppr: 'PPR023',
        adresse: 'Rue Al Amane, Agadir',
        email: 'badr.eddine@example.com',
        numeroTelephone: '+212600567892',
        experienceExterne: '5 années chez MechTech',
        experienceInterne: '8 années',
        divisionId: divisionMap['DCT'],
        informationsSupplementaires: ['Formation en mécanique'],
        image: 'https://via.placeholder.com/150?text=Badr+Eddine',
        anciennete: Math.floor((new Date('2025-06-02') - new Date('2012-09-01')) / (1000 * 60 * 60 * 24 * 365)),
      },
      {
        nomComplet: 'Rim El Amrani',
        dateNaissance: new Date('1987-12-20'),
        sexe: 'Femme',
        grade: 'Analyste Financier',
        dateRecrutement: new Date('2018-03-15'),
        diplome: 'Master en Finance',
        affectation: 'Gestion financière',
        situationFamiliale: 'Célibataire',
        missionPoste: 'Analyser les données financières',
        formationInitiale: 'École Supérieure de Commerce',
        activitePrincipale: 'Rapports financiers',
        cin: 'RE123459',
        ppr: 'PPR024',
        adresse: 'Avenue Mohammed V, Rabat',
        email: 'rim.elamrani@example.com',
        numeroTelephone: '+212600123459',
        experienceExterne: '2 années chez FinTech',
        experienceInterne: '3 années',
        divisionId: divisionMap['DCT'],
        informationsSupplementaires: ['Certificat en finance'],
        image: 'https://via.placeholder.com/150?text=Rim+El+Amrani',
        anciennete: Math.floor((new Date('2025-06-02') - new Date('2018-03-15')) / (1000 * 60 * 60 * 24 * 365)),
      },
      {
        nomComplet: 'Amine Khattabi',
        dateNaissance: new Date('1984-07-14'),
        sexe: 'Homme',
        grade: 'Coordinatrice',
        dateRecrutement: new Date('2016-02-01'),
        diplome: 'Licence en Logistique',
        affectation: 'Coordination logistique',
        situationFamiliale: 'Marié',
        missionPoste: 'Coordonner les flux logistiques',
        formationInitiale: 'Université Al Akhawayn',
        activitePrincipale: 'Planification logistique',
        cin: 'AK789014',
        ppr: 'PPR025',
        adresse: 'Rue Ibn Sina, Fès',
        email: 'amine.khattabi@example.com',
        numeroTelephone: '+212600789014',
        experienceExterne: '3 années chez LogiTech',
        experienceInterne: '6 années',
        divisionId: divisionMap['DFL'],
        informationsSupplementaires: ['Formation en logistique'],
        image: 'https://via.placeholder.com/150?text=Amine+Khattabi',
        anciennete: Math.floor((new Date('2025-06-02') - new Date('2016-02-01')) / (1000 * 60 * 60 * 24 * 365)),
      },
      {
        nomComplet: 'Leila Hassani',
        dateNaissance: new Date('1992-01-10'),
        sexe: 'Femme',
        grade: 'Analyste Financier',
        dateRecrutement: new Date('2021-06-01'),
        diplome: 'Master en Finance',
        affectation: 'Analyse financière',
        situationFamiliale: 'Célibataire',
        missionPoste: 'Analyser les données financières',
        formationInitiale: 'Université Cadi Ayyad',
        activitePrincipale: 'Rapports et prévisions',
        cin: 'LH345680',
        ppr: 'PPR026',
        adresse: 'Avenue Al Haouz, Marrakech',
        email: 'leila.hassani@example.com',
        numeroTelephone: '+212600345680',
        experienceExterne: '1 année chez FinCorp',
        experienceInterne: '1 année',
        divisionId: divisionMap['DFL'],
        informationsSupplementaires: ['Certificat en analyse financière'],
        image: 'https://via.placeholder.com/150?text=Leila+Hassani',
        anciennete: Math.floor((new Date('2025-06-02') - new Date('2021-06-01')) / (1000 * 60 * 60 * 24 * 365)),
      },
      {
        nomComplet: 'Tarek Benhima',
        dateNaissance: new Date('1978-06-08'),
        sexe: 'Homme',
        grade: 'Consultant',
        dateRecrutement: new Date('2011-04-15'),
        diplome: 'Master en Évaluation',
        affectation: 'Évaluation des performances',
        situationFamiliale: 'Marié',
        missionPoste: 'Évaluer les performances des équipes',
        formationInitiale: 'École Nationale de Gestion',
        activitePrincipale: 'Audit et évaluation',
        cin: 'TB901237',
        ppr: 'PPR027',
        adresse: 'Rue Al Amal, Tanger',
        email: 'tarek.benhima@example.com',
        numeroTelephone: '+212600901237',
        experienceExterne: '5 années chez EvalTech',
        experienceInterne: '9 années',
        divisionId: divisionMap['DPE'],
        informationsSupplementaires: ['Certificat en évaluation'],
        image: 'https://via.placeholder.com/150?text=Tarek+Benhima',
        anciennete: Math.floor((new Date('2025-06-02') - new Date('2011-04-15')) / (1000 * 60 * 60 * 24 * 365)),
      },
      {
        nomComplet: 'Imane Zaki',
        dateNaissance: new Date('1989-09-25'),
        sexe: 'Femme',
        grade: 'Analyste',
        dateRecrutement: new Date('2017-08-01'),
        diplome: 'Master en Statistiques',
        affectation: 'Analyse de performances',
        situationFamiliale: 'Célibataire',
        missionPoste: 'Analyser les données de performance',
        formationInitiale: 'Université Hassan II',
        activitePrincipale: 'Rapports et analyses',
        cin: 'IZ567893',
        ppr: 'PPR028',
        adresse: 'Avenue Mohammed VI, Casablanca',
        email: 'imane.zaki@example.com',
        numeroTelephone: '+212600567893',
        experienceExterne: '2 années chez StatTech',
        experienceInterne: '4 années',
        divisionId: divisionMap['DPE'],
        informationsSupplementaires: ['Formation en statistiques'],
        image: 'https://via.placeholder.com/150?text=Imane+Zaki',
        anciennete: Math.floor((new Date('2025-06-02') - new Date('2017-08-01')) / (1000 * 60 * 60 * 24 * 365)),
      },
      {
        nomComplet: 'Yassine Bennis',
        dateNaissance: new Date('1980-02-14'),
        sexe: 'Homme',
        grade: 'Manager RH',
        dateRecrutement: new Date('2013-05-01'),
        diplome: 'Master en Gestion RH',
        affectation: 'Gestion RH',
        situationFamiliale: 'Marié',
        missionPoste: 'Gérer les ressources humaines',
        formationInitiale: 'École Supérieure de Commerce',
        activitePrincipale: 'Planification RH',
        cin: 'YB123460',
        ppr: 'PPR029',
        adresse: 'Rue Al Wahda, Rabat',
        email: 'yassine.bennis@example.com',
        numeroTelephone: '+212600123460',
        experienceExterne: '4 années chez HRTech',
        experienceInterne: '8 années',
        divisionId: divisionMap['DRHF'],
        informationsSupplementaires: ['Certificat en gestion RH'],
        image: 'https://via.placeholder.com/150?text=Yassine+Bennis',
        anciennete: Math.floor((new Date('2025-06-02') - new Date('2013-05-01')) / (1000 * 60 * 60 * 24 * 365)),
      },
      {
        nomComplet: 'Khadija El Hafidi',
        dateNaissance: new Date('1993-04-12'),
        sexe: 'Femme',
        grade: 'Assistante RH',
        dateRecrutement: new Date('2021-03-01'),
        diplome: 'Licence en Gestion',
        affectation: 'Administration RH',
        situationFamiliale: 'Célibataire',
        missionPoste: 'Gérer les dossiers du personnel',
        formationInitiale: 'Université Ibn Zohr',
        activitePrincipale: 'Gestion administrative',
        cin: 'KE789015',
        ppr: 'PPR030',
        adresse: 'Avenue Al Massira, Agadir',
        email: 'khadija.elhafidi@example.com',
        numeroTelephone: '+212600789015',
        experienceExterne: '1 année chez AdminTech',
        experienceInterne: '1 année',
        divisionId: divisionMap['DRHF'],
        informationsSupplementaires: ['Formation en gestion administrative'],
        image: 'https://via.placeholder.com/150?text=Khadija+El+Hafidi',
        anciennete: Math.floor((new Date('2025-06-02') - new Date('2021-03-01')) / (1000 * 60 * 60 * 24 * 365)),
      },
      {
        nomComplet: 'Mehdi Fassi',
        dateNaissance: new Date('1982-10-05'),
        sexe: 'Homme',
        grade: 'Architecte',
        dateRecrutement: new Date('2014-07-01'),
        diplome: 'Master en Architecture',
        affectation: 'Conception urbaine',
        situationFamiliale: 'Marié',
        missionPoste: 'Concevoir des projets urbains',
        formationInitiale: 'École Nationale d’Architecture',
        activitePrincipale: 'Conception et planification',
        cin: 'MF345681',
        ppr: 'PPR031',
        adresse: 'Rue Al Amane, Marrakech',
        email: 'mehdi.fassi@example.com',
        numeroTelephone: '+212600345681',
        experienceExterne: '4 années chez ArchiTech',
        experienceInterne: '7 années',
        divisionId: divisionMap['DUE'],
        informationsSupplementaires: ['Certificat en architecture'],
        image: 'https://via.placeholder.com/150?text=Mehdi+Fassi',
        anciennete: Math.floor((new Date('2025-06-02') - new Date('2014-07-01')) / (1000 * 60 * 60 * 24 * 365)),
      },
      {
        nomComplet: 'Amina Sefrioui',
        dateNaissance: new Date('1988-03-20'),
        sexe: 'Femme',
        grade: 'Consultant',
        dateRecrutement: new Date('2018-09-01'),
        diplome: 'Master en Urbanisme',
        affectation: 'Développement urbain',
        situationFamiliale: 'Marié',
        missionPoste: 'Conseiller sur le développement urbain',
        formationInitiale: 'École d’Architecture de Rabat',
        activitePrincipale: 'Conseil et planification',
        cin: 'AS901238',
        ppr: 'PPR032',
        adresse: 'Avenue Mohammed V, Casablanca',
        email: 'amina.sefrioui@example.com',
        numeroTelephone: '+212600901238',
        experienceExterne: '2 années chez UrbanTech',
        experienceInterne: '3 années',
        divisionId: divisionMap['DUE'],
        informationsSupplementaires: ['Formation en urbanisme'],
        image: 'https://via.placeholder.com/150?text=Amina+Sefrioui',
        anciennete: Math.floor((new Date('2025-06-02') - new Date('2018-09-01')) / (1000 * 60 * 60 * 24 * 365)),
      },
      {
        nomComplet: 'Hicham Laaroussi',
        dateNaissance: new Date('1977-11-15'),
        sexe: 'Homme',
        grade: 'Manager',
        dateRecrutement: new Date('2011-02-01'),
        diplome: 'Master en Informatique',
        affectation: 'Gestion administrative',
        situationFamiliale: 'Marié',
        missionPoste: 'Superviser les équipes administratives',
        formationInitiale: 'École Nationale d’Ingénieurs',
        activitePrincipale: 'Coordination administrative',
        cin: 'HL567894',
        ppr: 'PPR033',
        adresse: 'Rue Al Amal, Rabat',
        email: 'hicham.laaroussi@example.com',
        numeroTelephone: '+212600567894',
        experienceExterne: '5 années chez AdminCorp',
        experienceInterne: '9 années',
        divisionId: divisionMap['DAEC'],
        informationsSupplementaires: ['Certificat en gestion administrative'],
        image: 'https://via.placeholder.com/150?text=Hicham+Laaroussi',
        anciennete: Math.floor((new Date('2025-06-02') - new Date('2011-02-01')) / (1000 * 60 * 60 * 24 * 365)),
      },
      {
        nomComplet: 'Samira Jilali',
        dateNaissance: new Date('1990-06-10'),
        sexe: 'Femme',
        grade: 'Analyste',
        dateRecrutement: new Date('2019-04-01'),
        diplome: 'Licence en Gestion',
        affectation: 'Analyse de données',
        situationFamiliale: 'Célibataire',
        missionPoste: 'Analyser les données administratives',
        formationInitiale: 'Université Mohammed V',
        activitePrincipale: 'Rapports et analyses',
        cin: 'SJ123461',
        ppr: 'PPR034',
        adresse: 'Avenue Al Massira, Fès',
        email: 'samira.jilali@example.com',
        numeroTelephone: '+212600123461',
        experienceExterne: '1 année chez DataTech',
        experienceInterne: '3 années',
        divisionId: divisionMap['DAEC'],
        informationsSupplementaires: ['Formation en analyse de données'],
        image: 'https://via.placeholder.com/150?text=Samira+Jilali',
        anciennete: Math.floor((new Date('2025-06-02') - new Date('2019-04-01')) / (1000 * 60 * 60 * 24 * 365)),
      },
      {
        nomComplet: 'Walid Cherif',
        dateNaissance: new Date('1985-08-22'),
        sexe: 'Homme',
        grade: 'Technicienne',
        dateRecrutement: new Date('2017-01-15'),
        diplome: 'BTS en Génie Civil',
        affectation: 'Infrastructure technique',
        situationFamiliale: 'Marié',
        missionPoste: 'Maintenir les infrastructures',
        formationInitiale: 'Institut Technique de Casablanca',
        activitePrincipale: 'Maintenance technique',
        cin: 'WC789016',
        ppr: 'PPR035',
        adresse: 'Rue Al Haouz, Marrakech',
        email: 'walid.cherif@example.com',
        numeroTelephone: '+212600789016',
        experienceExterne: '3 années chez InfraTech',
        experienceInterne: '5 années',
        divisionId: divisionMap['DAI'],
        informationsSupplementaires: ['Formation en génie civil'],
        image: 'https://via.placeholder.com/150?text=Walid+Cherif',
        anciennete: Math.floor((new Date('2025-06-02') - new Date('2017-01-15')) / (1000 * 60 * 60 * 24 * 365)),
      },
      // New employees for Cabinet division
      {
        nomComplet: 'Nabil El Khattabi',
        dateNaissance: new Date('1976-05-20'),
        sexe: 'Homme',
        grade: 'Manager',
        dateRecrutement: new Date('2012-03-01'),
        diplome: 'Master en Stratégie',
        affectation: 'Gestion stratégique',
        situationFamiliale: 'Marié',
        missionPoste: 'Superviser les initiatives stratégiques',
        formationInitiale: 'École Nationale de Commerce et de Gestion',
        activitePrincipale: 'Planification stratégique',
        cin: 'NE123462',
        ppr: 'PPR036',
        adresse: 'Avenue Mohammed V, Rabat',
        email: 'nabil.elkhattabi@example.com',
        numeroTelephone: '+212600123462',
        experienceExterne: '6 années chez StratCorp',
        experienceInterne: '9 années',
        divisionId: divisionMap['Cabinet'],
        informationsSupplementaires: ['Certificat en gestion stratégique'],
        image: 'https://via.placeholder.com/150?text=Nabil+El+Khattabi',
        anciennete: Math.floor((new Date('2025-06-02') - new Date('2012-03-01')) / (1000 * 60 * 60 * 24 * 365)),
      },
      {
        nomComplet: 'Hafsa Bennani',
        dateNaissance: new Date('1989-07-15'),
        sexe: 'Femme',
        grade: 'Consultant',
        dateRecrutement: new Date('2018-06-01'),
        diplome: 'Master en Management',
        affectation: 'Conseil stratégique',
        situationFamiliale: 'Célibataire',
        missionPoste: 'Fournir des conseils stratégiques',
        formationInitiale: 'Université Al Akhawayn',
        activitePrincipale: 'Analyse et recommandations',
        cin: 'HB789017',
        ppr: 'PPR037',
        adresse: 'Rue Al Amal, Casablanca',
        email: 'hafsa.bennani@example.com',
        numeroTelephone: '+212600789017',
        experienceExterne: '2 années chez ConsultCorp',
        experienceInterne: '4 années',
        divisionId: divisionMap['Cabinet'],
        informationsSupplementaires: ['Formation en gestion stratégique'],
        image: 'https://via.placeholder.com/150?text=Hafsa+Bennani',
        anciennete: Math.floor((new Date('2025-06-02') - new Date('2018-06-01')) / (1000 * 60 * 60 * 24 * 365)),
      },
      // New employees for SG division
      {
        nomComplet: 'Oussama El Fassi',
        dateNaissance: new Date('1978-09-10'),
        sexe: 'Homme',
        grade: 'Manager',
        dateRecrutement: new Date('2013-04-01'),
        diplome: 'Master en Administration',
        affectation: 'Coordination générale',
        situationFamiliale: 'Marié',
        missionPoste: 'Superviser la coordination générale',
        formationInitiale: 'École Nationale de Commerce',
        activitePrincipale: 'Gestion des opérations générales',
        cin: 'OE345682',
        ppr: 'PPR038',
        adresse: 'Avenue Hassan II, Marrakech',
        email: 'oussama.elfassi@example.com',
        numeroTelephone: '+212600345682',
        experienceExterne: '5 années chez AdminCorp',
        experienceInterne: '8 années',
        divisionId: divisionMap['SG'],
        informationsSupplementaires: ['Certificat en administration'],
        image: 'https://via.placeholder.com/150?text=Oussama+El+Fassi',
        anciennete: Math.floor((new Date('2025-06-02') - new Date('2013-04-01')) / (1000 * 60 * 60 * 24 * 365)),
      },
      {
        nomComplet: 'Fatima El Amrani',
        dateNaissance: new Date('1992-02-18'),
        sexe: 'Femme',
        grade: 'Assistante',
        dateRecrutement: new Date('2020-05-01'),
        diplome: 'Licence en Gestion',
        affectation: 'Support administratif',
        situationFamiliale: 'Célibataire',
        missionPoste: 'Assister dans la coordination générale',
        formationInitiale: 'Université Mohammed V',
        activitePrincipale: 'Gestion administrative',
        cin: 'FE901239',
        ppr: 'PPR039',
        adresse: 'Rue Ibn Battuta, Fès',
        email: 'fatima.elamrani@example.com',
        numeroTelephone: '+212600901239',
        experienceExterne: '1 année chez AdminTech',
        experienceInterne: '2 années',
        divisionId: divisionMap['SG'],
        informationsSupplementaires: ['Formation en gestion administrative'],
        image: 'https://via.placeholder.com/150?text=Fatima+El+Amrani',
        anciennete: Math.floor((new Date('2025-06-02') - new Date('2020-05-01')) / (1000 * 60 * 60 * 24 * 365)),
      },
    ];

    const insertedEmployees = await Employee.insertMany(employees);
    console.log('Employees inserted:', insertedEmployees.length);

    // Update divisions with employeeIds and managerId
    const managerAssignments = {
      'DAEC': 'ahmed.benali@example.com',
      'DAI': 'mohammed.elidrissi@example.com',
      'DAS': 'laila.chraibi@example.com',
      'DCT': 'khalid.saidi@example.com',
      'DFL': 'omar.tazi@example.com',
      'DPE': 'hassan.bouzidi@example.com',
      'DRHF': 'rachid.mernissi@example.com',
      'DUE': 'said.cherkaoui@example.com',
      'Cabinet': 'nabil.elkhattabi@example.com',
      'SG': 'oussama.elfassi@example.com',
    };

    for (const employee of insertedEmployees) {
      if (employee.divisionId) {
        await Division.findByIdAndUpdate(employee.divisionId, {
          $push: { employeeIds: employee._id },
        }, { upsert: true });
      }
      const divisionName = Object.keys(divisionMap).find(key => divisionMap[key].equals(employee.divisionId));
      if (divisionName && managerAssignments[divisionName] === employee.email) {
        await Division.findOneAndUpdate(
          { _id: employee.divisionId },
          { managerId: employee._id },
          { upsert: true }
        );
      }
    }

    // Verify division updates
    const updatedDivisions = await Division.find();
    updatedDivisions.forEach(div => {
      console.log(`Division ${div.name}: managerId=${div.managerId ? div.managerId : 'null'}, employeeIds=${div.employeeIds.length}`);
    });

    console.log('Database seeded successfully!');
  } catch (err) {
    console.error('Error seeding database:', err);
  } finally {
    await mongoose.connection.close();
  }
};

seedData();